---
language: python
python: 3.6
cache: pip

git:
  depth: 1

script:
  - set -e
  - python -m renderer
  - git rev-parse HEAD > public/fingerprint.txt
  - aws s3 sync public/ s3://bazile.www/ --delete
