#!/bin/bash -e

cd "$(dirname $(dirname $0))"

cd public


if [[ $# == 0 ]]; then
	set -- '--bind' '127.0.0.1'
fi

python3 -m http.server "$@" 2> /dev/null &
server_pid=$!
trap "kill $server_pid" EXIT

../scripts/build --watch
